### ISSUE TITLE
include non-ABS structures?

### ISSUE THREAD

**Issue by wfmackey** [runapp-aus/abscorr#13]
eg National Skills Commission's recent Australian Skills Classification.

I think it would be useful?

**Comment by MattCowgill** [comment]
I agree it would be useful. Maybe the package should be called `auscorr` or something if it's scope is going to be broader than ABS structures?

**Comment by wfmackey** [comment]
Woah huge. Currently the `absmapsdata` has a bunch of non-ABS structures (eg postcodes), and I don't think it causes _too_ much confusion. But it would make sense to rename while we can.

**Comment by MattCowgill** [comment]
Yeah fair, I don't think it's a huge issue if a package with `abs` in the name contains non-ABS stuff. But better to actively make that decision one way or the other now.

**Comment by wfmackey** [comment]
Let's leave the package open to including non-ABS structures, with the inclusion criteria that it is a structure developed by an official organisation in Australia.

New issue #20 for whether we should rename the package to make this more explicit.
