### ISSUE TITLE
Consistent naming convention for structures? 

### ISSUE THREAD

**Issue by daviddiviny** [runapp-aus/abscorr#17]
I don't really care what it is (but I am sure I will have opinions) but we should try and be consistent early on to make life easier in the future. 

Already the column-naming conventions of `anzsco` are `anzsic` are inconsistent. 

![image](https://user-images.githubusercontent.com/6833387/115165715-90fd9600-a0f2-11eb-95bc-adc7a2361871.png)

**Comment by wfmackey** [comment]
Agree! Starting out, my preference was to use digits as the levels in column names (`anzsco1` = 1 digit, etc). But this fell down at ANZSIC, which doesn't represent its levels with digits.

Given ANZSIC, the only consistent way is to use the names used in each of the structures. So:

```
anzsco_major = anzsco1
anzsco_submajor = anzsco2
anzsco_minor = anzsco3
anzsco_unit = anzsco4
anzsco_occupation = anzsco6

aced_foe_broad = aced_foe2
aced_foe_narrow = aced_foe4
aced_foe_detailed = aced_foe6

aced_qual_broad = aced_qual1
aced_qual_narrow =  aced_qual2
aced_qual_detailed =  aced_qual3
```

This is probably sensible!

**Comment by daviddiviny** [comment]
Sensible but not strictly tidy is it? In that there is information in column name?

**Comment by daviddiviny** [comment]
That is not necessarily a problem.

**Comment by wfmackey** [comment]
True! It isn't strictly tidy. Do you think it should be?

Where I have this package in the past, it has almost entirely been in this way:

```r
library(tidyverse)
library(abscorr)

# read some abs file
abs <- read_csv("some/abs/file.csv") %>% 
  rename(anzsco4 = `Occupation Name`)

anzsco4_levels <- abscorr::anzsco %>% 
  distinct(anzsco2, anzsco4)

# add anzsco levels and summarise
abs %>% 
  left_join(anzsco4_levels) %>% 
  count(anzsco2, wt = n)
```

and so having the `abscorr::anzsco` dataset in its wide form is useful. 

For a tidy alternative, something like:

```r
anzsco ← tribble(
~category_level, ~category_name, ~category_code,
"Major", "Managers", "1",
...
"Sub-major", "Chief Executives, General Managers and Legislators", "11",
etc
)
```
what would the use case be? (I'm sure there are plenty!)

**Comment by daviddiviny** [comment]
I don't think it does need to be tidy, but we could consider having a tidy version? It could be useful if people have mashed up different hierarchies or you want to look up the level?

**Comment by wfmackey** [comment]
Good idea!

**Comment by daviddiviny** [comment]
And can we agree that any column will append the word `code` if it is some kind of alphanumerical code?

**Comment by MattCowgill** [comment]
makes sense to me @daviddiviny

**Comment by wfmackey** [comment]
@daviddiviny this week I'll rename these variables (and make all required changes in the package, including in your #32 functions/tests. I'll also remove the factor variants (re the Original Issue: #1).
