### ISSUE TITLE
add function to return SEIFA scores per various spatial structures

### ISSUE THREAD

**Issue by mrjoh3** [runapp-aus/abscorr#19]
SEIFA scores are available at https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/2033.0.55.0012016?OpenDocument for a number of spatial areas. LGA is at  a reasonable size for Aus wide coverage.

@wfmackey is the intention of the package to store the data in the package or for the user to download from ABS when needed. The LGA excel is ~700kb. So if data stored in package it might get very big very quickly.

please assign this issue to me, I will make a start.

**Comment by mrjoh3** [comment]
the structure of the excel files are similar enough for lga, postcode, suburb, sa2 and sa1. So I will add option to pick the spatial area returned

**Comment by wfmackey** [comment]
Love it. 

For this, and more broadly, it might be good to have some distinction between `structures` and `data`. 

- `structures` should link to a specific ABS (and non-ABS) data structures/standards (ANZSCO, ASCED, ASGS, etc). There aren't _too many_ of these that they can't be stored within the package as compressed `rda` or `sf` objects. 

- `data` should be commonly-used(?) aggregated data that match those structures, like SEIFA scores matched to ASGS, population counts matched to everything, etc, etc, etc, etc. There can be many of these, and so probably best if a function pulls those numbers from somewhere on-demand.

**Comment by mrjoh3** [comment]
working draft completed at 1eeecf31bbf828b07c948f850f86fb54b5641433 will add to tests and docs before closing
