### ISSUE TITLE
numeric codes are currently stored as characters: good idea or nah?

### ISSUE THREAD

**Issue by wfmackey** [runapp-aus/abscorr#2]
Numeric codes are currently stored as characters rather than integers. This was originally done to preserve leading zeros that accompany some codes, some of the time. (eg "01", "02" etc, in the ASCED field of education structure). But it will likely cause issues with others. 

Should they be stored as an integer? Or should there be an additional variable containing the integer variants?

**Comment by nerskin** [comment]
What issues will using strings cause? The codes are not numbers, and you shouldn't ever be doing arithmetic with them.

**Comment by nerskin** [comment]
Also: using strings is a more natural way of working with codes where hierarchies in the classifications are represented using prefixing

**Comment by nerskin** [comment]
Also also: meshblock ids are too big to represent as 32-bit integers! They're eleven digits and get converted to floating point if you try

**Comment by wfmackey** [comment]
Good good good reasons for "nah". The only use-case is reading a csv/excel file in, where the codes will be converted to numerics by default, and then trying to `_join`. But that is not a good reason.
