### ISSUE TITLE
is `abscorr` a good name?

### ISSUE THREAD

**Issue by wfmackey** [runapp-aus/abscorr#20]
Mentioned by a couple of people now, on both the `abs` and the `corr` portions of the name (100% of the name for those counting). 

@MattCowgill (https://github.com/runapp-aus/abscorr/issues/13#issuecomment-821917024) noted that if the package would include non-ABS structures, it might be better to name it something like `auscorr`. 

@lazappi mentioned:
> before I read the post I assumed `abscorr` would involve correlating ABS data. If it is just a set of data structures maybe `abscore` would be clearer? Possibly there is some terminology I’m not familiar with though.

Combining these ideas gives `auscore`, which I [think](https://i-d.vice.com/en_uk/article/nen9jd/is-auscore-the-next-big-thing) is [funny](https://open.spotify.com/playlist/37i9dQZF1E4wbqiDkqaMJl). But might not be exactly what we're looking for. 

Suggestions welcome.

**Comment by wfmackey** [comment]
Some unimaginative options:

- `abscorr`: ABS correspondences
- `abscat` or `catabs: a catalogue of ABS structures
- `acoas`: A Catalogue Of ABS Structures
- `absstructures`: maybe too long; don't like the double s
- `ausdata`: cast a wide net that leaves more room to move, but not very explicit about what the package aims to do now; surprisingly doesn't look like it's taken yet. 
- `ausdatastructures` or `ausdatastruct`: more explicit than the above

**Comment by MattCowgill** [comment]
I'm not into `absstructures` but don't hate any of the others. I'd probably lean towards `auscore` or `ausdata` but I don't think it's a problem to keep `abs` in the name

**Comment by MattCowgill** [comment]
🚀

**Comment by daviddiviny** [comment]
What about `appcat` - Australian Public Policy Categorisations? That way it can have a link to `runapp`?

**Comment by mrjoh3** [comment]
I write like appcat or ausdata, for simplicity perhaps ausdata is the clearest

**Comment by wfmackey** [comment]
I like `appcat` (the sticker writes itself), and `ausdata`. I would prefer `appcat` if the package focussed solely on common Australian data classifications; and `ausdata` if the package is likely to grow to include more _data_ (see https://github.com/runapp-aus/abscorr/issues/24#issuecomment-822967415)

Given the latter looks to be more likely, I may be in favor of `ausdata`?

**Comment by MattCowgill** [comment]
`ausdata` gives a clearer sense of what the package does, it gets my vote

**Comment by daviddiviny** [comment]
To me `ausdata` sounds like a package full of data. How about `ausdatatools`? - Tools for working with Australian data.

**Comment by MattCowgill** [comment]
Fair point @daviddiviny. 

Another alternative: I’d be happy to donate the name `strayr` and bring over the functions from that package

**Comment by wfmackey** [comment]
They're all fine names! From the above there are a few good options that people are mostly happy with below. I will include the _very_ generous offer from @MattCowgill of `strayr` because it is my favourite package name of all time and it would be great for this package to include those functions.

If you care, vote in the poll below by Friday. Pros and cons for each of these, but we gotta land on something. We'll rename this package with the winner this Friday:

/polls "strayr" "ausdatatools" "appcat" "runappcat"

**Comment by wfmackey** [comment]
They're all fine names! From the above there are a few good options that people are mostly happy with below. I will include the _very_ generous offer from @MattCowgill of `strayr` because it is my favourite package name of all time and it would be great for this package to include those functions.

If you care, vote in the poll below by Friday. Pros and cons for each of these, but we gotta land on something. We'll rename this package with the winner this Friday:

/polls "strayr" "ausdatatools" "appcat" "runappcat"

**Comment by wfmackey** [comment]
(lol a poll is meant to appear: https://github.com/evenchange4/gh-polls-bot)

**Comment by wfmackey** [comment]
Vote via emoji reaction:

🎉  `strayr` 
🚀  `ausdatatools` 
😄 `appcat` 
👀  `runappcat`

**Comment by rensa** [comment]
If the package includes non-ABS data, what other kinds of data does it include? `ausdata` is nice but very broad!

**Comment by adam-gruer** [comment]
ozcodes

**Comment by adam-gruer** [comment]
classyoz ozclassi

**Comment by adam-gruer** [comment]
I rules

**Comment by adam-gruer** [comment]
Ozrachies
