### ISSUE TITLE
add devtools::document() and pkgdown::build_site() to github actions

### ISSUE THREAD

**Issue by wfmackey** [runapp-aus/abscorr#25]
re: https://github.com/runapp-aus/abscorr/pull/23#issue-617956177

**Comment by wfmackey** [comment]
#26 has automated `pkgdown::build_site()` via github actions.

**Comment by bryceroney** [comment]
Looks like my most recent PR killed website updating, just need to change the github pages source from the `docs` folder to the `gh-pages` branch.

![image](https://user-images.githubusercontent.com/6660301/117892192-9e75fc80-b2fb-11eb-95a9-904b73131e67.png)

**Comment by wfmackey** [comment]
Sorry for being slow on this. Fixed now.
