### ISSUE TITLE
Make authors appear on pkgdown page

### ISSUE THREAD

**Issue by wfmackey** [runapp-aus/abscorr#33]
Currently this the 'Developers' section of the pckdown page:
![image](https://user-images.githubusercontent.com/30094143/120106404-27b47c80-c1a0-11eb-8e74-6944083d8025.png)
which needs to be expanded to include all contributors. I have tried adding `c("aut", "cre")` to authors on DESCRIPTION (https://github.com/runapp-aus/abscorr/commit/2963b1038bf4fd52eac2d7f5badeb48f3f3dee76), but not appearing yet. I'll look into this this week unless anyone else has a solution.

**Comment by wfmackey** [comment]
@bryceroney do you know what I'm missing here?

**Comment by bryceroney** [comment]
I'll take a look while working on [#35](https://github.com/runapp-aus/abscorr/issues/35#issuecomment-851104333_)

**Comment by bryceroney** [comment]
Worked it out, you need to [use `Authors@R`](https://r-pkgs.org/description.html?q=authors#author) in the `DESCRIPTION` file to be able to list multiple authors.
