### ISSUE TITLE
Setup documentation using pkgdown

### ISSUE THREAD

**Issue by mrjoh3** [runapp-aus/abscorr#7]
pkgdown is a great way to display documentation and vignettes. I am happy to make a start (if you have not already) and submit a pull request

**Comment by wfmackey** [comment]
Excellent idea! Go for it.

**Comment by wfmackey** [comment]
Thanks @mrjoh3. The pkgdown website can now be found here: https://runapp-aus.github.io/abscorr/

**Comment by wfmackey** [comment]
Ah, sorry, the `docs/` folder hasn't been uploaded to Github (it is in `.gitignore`), so I can't point Github Pages to it. @mrjoh3 can you remove this from `.gitignore`? Or is there a better way?

**Comment by wfmackey** [comment]
Fixed in #16
